server:
  port: 18080
#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.66.5:8761/eureka/

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ppx-sofang
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  http:
    multipart:
      enable: true
      location: ./tmp/atai/images
      file-size-threshold: 5MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  # email 注意替换成自己邮箱的配置
  mail:
    host: smtp.163.com
    username: flyzfq@163.com
    password: wali123
    properties.mail.smtp.auth: true

  devtools:
    restart:
      exclude: templates/**,static/**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    password: root
    pool:
      max-active: 200
      max-wait: 1
      max-idle: 10
#  session:
#    store-type: redis

  zipkin:
    base-url: http://localhost:9411  #指定Zipkin server地址
    sleuth:
      sampler:
        probability: 1


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atdb?charset=utf8mb4&useSSL=false
#    url: jdbc:mysql://106.13.66.5:3306/atdb?charset=utf8mb4&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update



  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: atai
#  jpa:
#    data
#    database-platform:org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql:true
#    hibernate.ddl-auto:update
#logging:
#  config: logback.xml

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin

bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F

elasticsearch:
  cluster:
    name: atai
  host: localhost
  port: 90

logging:
  level:
    com.ppx.soufang.service.search: debug
    org:
      hibernate:
        SQL: debug

qiniu:
  AccessKey: GVD-MVQEoOiJOt7yNBDo-JrOKWHB33eZN2JmDFC6
  SecretKey: sHnl57ZXtStejn7GgY5VF3lnm1CxMJ3hcayexAWz
  Bucket: lakers
  cdn:
    prefix: http://7xo6gy.com1.z0.glb.clouddn.com/

aliyun:
  sms:
    accessKey: LTAISjYxxr5qLmio
    accessKeySecret: pkqEMJIcVQV8G5fkNEQNDQV7rsntKV
    template:
      code: SMS_95590008