spring:
  application:
    name: ppx-config
  cloud:
    config:
      server:
        git:
          username: root
          password: root
          uri: https://github.com/ATai2/ppxbi/ppx-config
          search-paths: /properties
server:
  port: 7001

