server:
  port: 7001

spring:
  application:
    name: ppx-config
  cloud:
    config:
      server:
        git:
#          username: root
#          password: root
          uri: git@github.com:ATai2/ppxbi.git
          search-paths: /ppx-config/properties/**
      label: master

