version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
#    volumes:
#    - ./esdata:/usr/share/elasticsearch/data
    networks:
    - efknet
    ports:
    - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    container_name: kibana
    networks:
    - efknet
    ports:
    - "5601:5601"


networks:
  efknet: