version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    volumes:
        - ./esdata:/usr/share/elasticsearch/data
#    networks:
#    - efknet
    ports:
    - "9200:9200"

  kibana:
    image: kibana:7.4.0
    container_name: kibana
#    networks:
#    - efknet
    ports:
    - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
#    networks:
#    - efknet
    ports:
    - "9411:9411"


#volumes:
#  data:











