server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.66.5:8761/eureka/
  instance:
    instance-id: power-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
spring:
  application:
    name: ppx-power

  redis:
    host: localhost
    port: 6379

  zipkin:
    base-url: http://localhost:9411  #指定Zipkin server地址
    sleuth:
      sampler:
        probability: 1
    storage:
      type: elasticsearch
      elasticsearch:
        cluster: elasticsearch
        hosts: http://localhost:9200
        index: zipkin

management:
  endpoints:
    web:
      exposure:
        include: '*'


