version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - ./docker.sock:/var/run/docker.sock
  kafka-manager:
    image: kafkamanager/kafka-manager
    ports:
      - "9001:9000"
    depends_on:
      - kafka
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181




#  docker run -d --name kafka-manager \--link zookeeper:zookeeper \--link kafka:kafka -p 9001:9000
#  \--restart=always \--env ZK_HOSTS=zookeeper:2181 \sheepkiller/kafka-manager









