server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.66.5:8761/eureka/

spring:
  application:
    name: ppx-userManagement
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    pool:
      max-active: 200
      max-wait: 1
      max-idle: 10

  zipkin:
    base-url: http://localhost:9411  #指定Zipkin server地址
    sleuth:
      sampler:
        probability: 1


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atdb?charset=utf8mb4&useSSL=false
#    url: jdbc:mysql://106.13.66.5:3306/atdb?charset=utf8mb4&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  jpa:
#    data
#    database-platform:org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql:true
#    hibernate.ddl-auto:update
#logging:
#  config: logback.xml

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5

management:
  endpoints:
    web:
      exposure:
        include: '*'

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin

bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F