server:
  port: 8990

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
#  profiles:
#    active: dev
  application:
    name: ppx-es

  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/atdb?charset=utf8mb4&useSSL=false
#    schema: classpath:db/shema.sql
#    data: classpath:db/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#security:
#  basic:
#    enabled: false

#  jpa:
#    data
#    database-platform:org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql:true
#    hibernate.ddl-auto:update
#logging:
#  config: logback.xml

#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/atdb?charset=utf8mb4&useSSL=false
#  spring.datasource.password=root
#  spring.datasource.username=root
#
#  spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.ddl-auto=validate
#  logging.level.org.hibernate.SQLQuery=debug
#
#  spring.session.store-type=hazelcast
#logging:
#  level: debug
