server:
  port: 9100

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://106.13.66.5:8761/eureka/

spring:
  application:
    name: ppx-px-web

