server:
  port: 9100
  servlet:
    context-path: /sell

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://106.13.66.5:8761/eureka/

spring:
  application:
    name: ppx-px-web

  redis:
    host: 106.13.66.5
    port: 6379
    password: rootatai
    timeout: 1000

