server:
  port: 5001


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

eureka:
  client:
    service-url:
      defaultZone: "http://106.13.66.5:8761/eureka/"
spring:
  application:
    name: ppx-gateway
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:8081
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1

      - id: host_route2
        uri: http://localhost:8082
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1

      - id: user
        uri: lb://ppx-userManagement
        predicates:
          - Path=/user/**
