version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    volumes:
        - ./esdata:/usr/share/elasticsearch/data
#    networks:
#    - efknet
    ports:
    - "9200:9200"

  kibana:
    image: kibana:7.4.0
    container_name: kibana
#    networks:
#    - efknet
    ports:
    - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
     - zipkin.storage.type= elasticsearch
     - zipkin.storage.StorageComponent= elasticsearch
     - zipkin.storage.elasticsearch.cluster= elasticsearch
     - zipkin.storage.elasticsearch.hosts= elasticsearch:9200
     - zipkin.storage.elasticsearch.max-requests=64
     - zipkin.storage.elasticsearch.index=zipkin
     - zipkin.storage.elasticsearch.index-shards=5
     - zipkin.storage.elasticsearch.index-replicas=1
#    networks:
#    - efknet
    ports:
    - "9411:9411"


# add zk
  zoo1:
    image: zookeeper:3.4.14
    restart: always
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.4.14
    restart: always
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.4.14
    restart: always
    container_name: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888



  admin:
    image: apache/dubbo-admin
    depends_on:
      - zoo1
    ports:
      - 8080
    environment:
      - admin.registry.address=zookeeper://zoo1:2181
      - admin.config-center=zookeeper://zoo1:2181
      - admin.metadata-report.address=zookeeper://zoo1:2181
#volumes:
#  data:











